### ISSUE TITLE
Banshee SDMA not working with non-zero tcdm start

### ISSUE THREAD

**Issue by noah95** [pulp-platform/snitch#108]
when `memory.tcdm.start` is set to an address different from `0x0`, the DMA doesn't perform the proper loads/stores anymore. 

This may be due to a wrong address used in `binary_store`/`binary_load` or inconsistencies between the `tcdm` and `memory` data structures used to hold memory.

**Comment by paulsc96** [comment]
Currently, the DMA cannot perform loads/stores on TCDM at all as `binary_load` and `binary_store` do not map the TCDM.

Is there something specific related to the position of the TCDM (`memory.tcdm.start`) that causes further problems I do not see? If yes, please describe a sensitizing case. Otherwise, the above PR should fix the issue.
