### ISSUE TITLE
/usr/bin/env: 'python3\r': No such file or directory

### ISSUE THREAD

**Issue by davemap** [pulp-platform/snitch#42]
`ls: cannot access 'trace_hart_*.dasm': No such file or directory
/repo/hw/system/snitch_cluster/../../../util/clustergen.py -c cfg/cluster.default.hjson -o .
/usr/bin/env: 'python3\r': No such file or directory`

Hi, I have downloaded the docker container and tried to run the first make command in the Getting Started tutorial and I am getting these errors and results in the bin folder not being created. Is there something I'm doing wrong?

Thanks in advance

**Comment by zarubaf** [comment]
Awesome you gave it a try and sorry it didn’t work out. To me the line endings look fishy. Is it possible that your native system is Windows?

We might need to change how the files are checked out for such a system.

**Comment by davemap** [comment]
Thank you. Yeah, I am running the docker container in Windows, I attempted to use the docker container I'm a WSL2 centos7 distro but it wouldn't let me start docker. I might try and set up a dual boot later today with Ubuntu, though I'd there's something simple I can do to get it running on windows the would be amazing.

**Comment by zarubaf** [comment]
Unfortunately, I don't have a Windows machine at hand right now. Looking at the [GitHub Help](https://docs.github.com/en/github/using-git/configuring-git-to-handle-line-endings) it seems you could:

1. Add a `.gitattributes` file containing:
   ```
   * text eol=lf
   ```
2. Delete all files except `.git` directory (commit changes before doing that so that if you have some locally so that you do not lose your work).
   ```
   $ git restore .
   ```
3. That should give you a new checkout with Linux file endings (and enable the Python script to work).

If that helps we could think about adding the `.gitattributes` file to the repository. I am not sure how editing such files natively on Windows works though, I think some editors are more clever than others (VS Code vs. Notepad for example).

I thought that Docker has an experimental WSL2 backend. That is probably the easiest route to go down (for long-term development sanity). Let me know if that helps, or if you have any follow-up questions :-)

**Comment by davemap** [comment]
I got the make file to work on an Ubuntu WSL2 which I then opened the docker in so I'm making progress :-) I've now got the stage where we run the benchmark on the Verilator model. It then seems to hang here:
![image](https://user-images.githubusercontent.com/47156308/108085263-0dc9b080-706d-11eb-8d6e-fdef062be2de.png)
Is it supposed to do something or does this run indefinitely? I used Ctrl+Z to stop the process and try to use the make traces command but it gives me errors about trace_hart_00000000.txt.
Sorry, I am very new to all of the RISC-V stuff, so thank you very much for all your help :)

**Comment by fabianschuiki** [comment]
This is indeed very strange. Especially the warning about tohost/fromhost should not be there. Looks like something in the compilation chain or the RISC-V frontend server is fishy. The test is supposed to terminate after around 1-5 minutes, depending on how fast your machine is. It should also print a runtime statistic of the matrix multiplication it executes, but that relies on the fesvr/tohost/fromhost, which won't be printed due to the warning above.

Also quite strange that you ran into the `\r` trouble even within the docker container. I'd expect this environment to be a pretty pristine Linux setup, and not be encumbered with Windows line endings.

@zarubaf Maybe a good check would be to add benchmark execution inside the docker container to CI; what do you think?

**Comment by zarubaf** [comment]
@davemap That was indeed a small issue in our build system. @fabianschuiki has just fixed this #49. Maybe you want to give it a try again? 

Closing this issue for now, but feel free to re-open it in case it persists.
