### ISSUE TITLE
Repeated SSR configuration [enhancement]

### ISSUE THREAD

**Issue by dbernhard-0x7CD** [pulp-platform/snitch#451]
While developing applications for the snitch we've come up with a potential improvement:

When the developer configures only one SSR he does not know if the other registers may have still some configuration and will also behave as SSR when we call `snrt_ssr_enable()`. 

So we'd propose to have some function like `snrt_ssr_clear()` which resets all registers (that they behave like normal registers) and the developer knows that all registers he configures afterwards will be enabled when calling `snrt_ssr_enable()` and no other registers.

**Comment by paulsc96** [comment]
Do you have an example on when this functionality may be helpful? For most config registers, the reset value is not necessarily helpful for real streams, so you would probably set them initially anyways and then leave them unchanged for following streams.

Can you elaborate on what you mean by "normal registers"? The launch registers having side effects is intentional, and the lower-address registers having some field restrictions and being shadowed are intentional design choices, too.

**Comment by dbernhard-0x7CD** [comment]
As it's semantically incorrect (as mentioned in #449) to use one register as SSR and another as a regular FPR this is needless.

I meant to use ft1 as a regular FPR / normal register (or actually the compiler) and ft0 as SSR.

**Comment by paulsc96** [comment]
just for completeness: you _can_ use some registers as SSRs and some as FPRs simultaneously; it's just that the subset of registers connected in HW to SSR datapaths (`ft0`, `ft1`, and `ft2` by default) can only switched into and out of SSR mode together, but all other FPRs continue to work as regular registers even while SSRs are enabled, so you could use `ft3` and all other non-SSR registers as temporaries.
